cookietemple_version: '1.3.10 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: depdive
project_slug_no_hyphen: depdive
template_version: '2.0.1 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: nasifimtiazohi
creator_github_username: nasifimtiazohi
is_github_repo: true
is_repo_private: false
is_github_orga: false
full_name: Nasif Imtiaz
email: nasifimtiaz88@gmail.com
project_name: depdive
project_short_description: Performs security checks for a dependency update
version: 0.0.29
license: MIT
